site_name: "Shishlina Anna, documentation"
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'pink'

nav:
  - Home: index.md
  - Lab №1:
    - Task 1: lab1/task_1.md
    - Task 2: lab1/task_2.md
    - Task 3: lab1/task_3.md
    - Task 4: lab1/task_4.md
  - Lab №2:
    - Task: lab2/lab.md
  - Lab №3:
    - Task: lab3/lab.md
